# Generated by Django 4.2.2 on 2023-09-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
