# Generated by Django 4.2.2 on 2023-10-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mart', '0004_cartitem_remove_order_products_delete_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Mart.product'),
        ),
    ]
