# Generated by Django 4.2.2 on 2023-10-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mart', '0007_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
